export type VenueStatus = "active" | "inactive";

export type VenueDocument = {
  id?: string;
  venueId?: string;
  category: string;
  fileName: string;
  filePath: string;
  fileType: string;
  fileSize: number;
  uploadedAt: string;
};

export type VenueProfile = {
  id: string;
  name: string;
  venueType: string;
  status: VenueStatus;
  addressLine1: string;
  city: string;
  stateRegion?: string;
  postalCode?: string;
  country: string;
  description?: string;
  imageUrl?: string;
  maxCapacity: number;
  indoorCapacity: number;
  outdoorCapacity: number;
  curfewTime?: string;
  noiseRestriction?: string;
  ageRestriction?: string;
  wheelchairAccessible: boolean;
  parkingAvailable: boolean;
  facilities: string[];
  otherFacilities?: string;
  venueManagerName?: string;
  venueManagerPhone?: string;
  bookingContactName?: string;
  bookingContactEmail?: string;
  financeContactName?: string;
  financeContactPhone?: string;
  financeContactEmail?: string;
  preferredContactMethod?: string;
  operationsNotes?: string;
  depositRequired: boolean;
  depositAmountCents: number;
  depositDueTerms?: string;
  hireFeeCents: number;
  paymentTerms?: string;
  barSplitPercent?: number;
  minimumSpendCents: number;
  securityRequired: boolean;
  equipmentProvided: boolean;
  smokingAllowed: boolean;
  lateLicense: boolean;
  timezone?: string;
  parkingDetails?: string;
  loadInDetails?: string;
  loadOutDetails?: string;
  addedDate: string;
  /** User id of the team member who added this venue. */
  createdBy?: string;
  createdAt: string;
  updatedAt: string;
  documents: VenueDocument[];
};

export type VenueDraft = {
  name: string;
  venueType: string;
  status: VenueStatus;
  addressLine1: string;
  city: string;
  stateRegion: string;
  postalCode: string;
  country: string;
  description: string;
  imageUrl: string;
  maxCapacity: number;
  indoorCapacity: number;
  outdoorCapacity: number;
  curfewTime: string;
  noiseRestriction: string;
  ageRestriction: string;
  wheelchairAccessible: boolean;
  parkingAvailable: boolean;
  facilities: string[];
  otherFacilities: string;
  venueManagerName: string;
  venueManagerPhone: string;
  bookingContactName: string;
  bookingContactEmail: string;
  financeContactName: string;
  financeContactPhone: string;
  financeContactEmail: string;
  preferredContactMethod: string;
  operationsNotes: string;
  depositRequired: boolean;
  depositAmountCents: number;
  depositDueTerms: string;
  hireFeeCents: number;
  paymentTerms: string;
  barSplitPercent: number;
  minimumSpendCents: number;
  securityRequired: boolean;
  equipmentProvided: boolean;
  smokingAllowed: boolean;
  lateLicense: boolean;
  timezone: string;
  parkingDetails: string;
  loadInDetails: string;
  loadOutDetails: string;
  documents: VenueDocument[];
};
