export type ArtistStatus = "active" | "inactive" | "archived";
export type ArtistReach = "local" | "national" | "international";
export type ArtistSocialPlatform = "instagram" | "tiktok" | "spotify" | "soundcloud" | "youtube";

export type ArtistSocialLink = {
  id?: string;
  platform: ArtistSocialPlatform;
  url: string;
};

export type ArtistDocument = {
  id?: string;
  artistId?: string;
  category: string;
  fileName: string;
  filePath: string;
  fileType: string;
  fileSize: number;
  uploadedAt: string;
};

export type ArtistProfile = {
  id: string;
  name: string;
  artistType: string;
  genres: string[];
  status: ArtistStatus;
  classification?: string;
  city?: string;
  country?: string;
  reach: ArtistReach;
  bio?: string;
  promoImageUrl?: string;
  contactName?: string;
  contactRole?: string;
  email?: string;
  phone?: string;
  preferredContactMethod?: string;
  agencyName?: string;
  managementCompany?: string;
  territory?: string;
  representedArtists: string[];
  internalNotes?: string;
  reliabilityRating?: number;
  typicalFeeCents: number;
  depositRequired: boolean;
  depositAmountCents: number;
  bookingNotes?: string;
  tags: string[];
  addedDate: string;
  createdAt: string;
  updatedAt: string;
  socialLinks: ArtistSocialLink[];
  documents: ArtistDocument[];
};

export type ArtistDraft = {
  name: string;
  artistType: string;
  genres: string[];
  status: ArtistStatus;
  classification: string;
  city: string;
  country: string;
  reach: ArtistReach;
  bio: string;
  promoImageUrl: string;
  contactName: string;
  contactRole: string;
  email: string;
  phone: string;
  preferredContactMethod: string;
  agencyName: string;
  managementCompany: string;
  territory: string;
  representedArtists: string[];
  internalNotes: string;
  reliabilityRating: number;
  typicalFeeCents: number;
  depositRequired: boolean;
  depositAmountCents: number;
  bookingNotes: string;
  tags: string[];
  socialLinks: ArtistSocialLink[];
  documents: ArtistDocument[];
};

export type VenueStatus = "active" | "inactive";

export type VenueDocument = {
  id?: string;
  venueId?: string;
  category: string;
  fileName: string;
  filePath: string;
  fileType: string;
  fileSize: number;
  uploadedAt: string;
};

export type VenueProfile = {
  id: string;
  name: string;
  venueType: string;
  status: VenueStatus;
  addressLine1: string;
  city: string;
  stateRegion?: string;
  postalCode?: string;
  country: string;
  description?: string;
  imageUrl?: string;
  maxCapacity: number;
  indoorCapacity: number;
  outdoorCapacity: number;
  curfewTime?: string;
  noiseRestriction?: string;
  ageRestriction?: string;
  wheelchairAccessible: boolean;
  parkingAvailable: boolean;
  facilities: string[];
  otherFacilities?: string;
  venueManagerName?: string;
  venueManagerPhone?: string;
  bookingContactName?: string;
  bookingContactEmail?: string;
  financeContactName?: string;
  financeContactPhone?: string;
  financeContactEmail?: string;
  preferredContactMethod?: string;
  operationsNotes?: string;
  depositRequired: boolean;
  depositAmountCents: number;
  depositDueTerms?: string;
  hireFeeCents: number;
  paymentTerms?: string;
  barSplitPercent?: number;
  minimumSpendCents: number;
  securityRequired: boolean;
  equipmentProvided: boolean;
  smokingAllowed: boolean;
  lateLicense: boolean;
  timezone?: string;
  parkingDetails?: string;
  loadInDetails?: string;
  loadOutDetails?: string;
  addedDate: string;
  createdAt: string;
  updatedAt: string;
  documents: VenueDocument[];
};

export type VenueDraft = {
  name: string;
  venueType: string;
  status: VenueStatus;
  addressLine1: string;
  city: string;
  stateRegion: string;
  postalCode: string;
  country: string;
  description: string;
  imageUrl: string;
  maxCapacity: number;
  indoorCapacity: number;
  outdoorCapacity: number;
  curfewTime: string;
  noiseRestriction: string;
  ageRestriction: string;
  wheelchairAccessible: boolean;
  parkingAvailable: boolean;
  facilities: string[];
  otherFacilities: string;
  venueManagerName: string;
  venueManagerPhone: string;
  bookingContactName: string;
  bookingContactEmail: string;
  financeContactName: string;
  financeContactPhone: string;
  financeContactEmail: string;
  preferredContactMethod: string;
  operationsNotes: string;
  depositRequired: boolean;
  depositAmountCents: number;
  depositDueTerms: string;
  hireFeeCents: number;
  paymentTerms: string;
  barSplitPercent: number;
  minimumSpendCents: number;
  securityRequired: boolean;
  equipmentProvided: boolean;
  smokingAllowed: boolean;
  lateLicense: boolean;
  timezone: string;
  parkingDetails: string;
  loadInDetails: string;
  loadOutDetails: string;
  documents: VenueDocument[];
};

export type SupabaseSession = {
  accessToken: string;
  refreshToken?: string;
  expiresAt?: number;
  user: {
    id: string;
    email?: string;
  };
};
